post http://localhost:3001/register/
Content-Type: application/json

{
   "username": "sriramana",
    "password": "he@123"

}

###
post http://localhost:3001/uploadFile/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyaWthbnRoIiwiaWF0IjoxNjM5MDU0NjA4fQ.6AGBFFfWybBbrS6yeWDAKrwEEFUkCogndwrA19Em5jM

###
get http://localhost:3001/getEntriesData/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyaWthbnRoIiwiaWF0IjoxNjM5NTUzODAzfQ.A4cNEScG_xrAPkQL-bNakx1vg-3_TscPMQBpAImEmJ4
